### ISSUE TITLE
[TASK] Separate config requirements for each relayer component/sub-system

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#195]
### Overview

The relayer system is composed of three main components. Each of these components should be thought of as entirely separate because they could be handled by different entities entirely.

1. Private transaction relaying 
2. Data querying (for zero-knowledge proof generation)
3. Event listening, proposing, and signature relaying (of DKG proposals where the relayer acts like an oracle)

However, currently users are unable to run each component separately or distinctively. For example, the configuration requirements for governance relaying also makes the relayer available for private tx relaying and data querying. We need to modify the configuration options so that users who ONLY want to participate in governance relaying can do so without also relaying private txs / data querying. 

### Use stories

- [ ] As a user, I want to operate a relayer so that I can relay transactions privately. 
- [ ] As a user, I want to operate a relayer so that I can participate in governance relaying.
- [ ] As a user, I want to operate a relayer so that I can participate in zero-knowledge proof generation and serving up data. 

## SPEC
Adding `features`  struct to `WebbRelayerConfig`  which can be used to configure the relayer with different options. By default, all features are enabled.
**Note** :  In order to run relayer for data querying, relayer should also be configured for governance relaying
                   Data querying option will only make leaves API endpoint accessible.

```rust
/// FeaturesConfig is the configuration for running relayer with option.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, Default)]
#[serde(rename_all = "kebab-case")]
pub struct FeaturesConfig {
    /// Enable data quering for leaves
    pub data_query: bool,
    /// Enable governance relaying
    pub governance_relay: bool,
    /// Enable private tx relaying
    pub private_tx_relay: bool,
}

pub struct WebbRelayerConfig {
    #[serde(default)]
    pub evm: HashMap<String, EvmChainConfig>,
    #[serde(default)]
    pub substrate: HashMap<String, SubstrateConfig>,
    /// Configuration for running relayer
    ///
    /// by deafult all features are enabled
    /// Features:
    /// 1. Data quering for leaves
    /// 2. Governance relaying
    /// 3. Private transaction relaying
    #[serde(default)]
    pub features: FeaturesConfig,
}
```
### Example
Here is an example of how to configure a relayer for relaying private tx for evm
```rust
port = 9955
.
.
[features]
data-query = false
governance-relay = false
```

**Comment by dutterbutter** [comment]
@shekohex based on our discussion please provide your thoughts on a potential approach / solution.

**Comment by shekohex** [comment]
I will be working on a spec today to help pushing this forward and solve this issue.
