### ISSUE TITLE
[BUG] Relaying roots for VAnchor 8-side fails inconsistently

### ISSUE THREAD

**Issue by nepoche** [webb-tools/relayer#204]
Using the updates to localnet config: https://github.com/webb-tools/relayer/pull/203

With the following localnet: https://github.com/webb-tools/evm-localnet/pull/4

And the appropriate fixtures: https://github.com/webb-tools/protocol-solidity-fixtures/pull/5

Sometimes, the relayer does not relay roots on VAnchor deposit:

https://user-images.githubusercontent.com/16654909/175315608-b378db37-67eb-4b60-a5a8-ff601496ebb0.mov

**Comment by shekohex** [comment]
I suspected it is related to this match stmt here: https://github.com/webb-tools/relayer/blob/c3e29a7303008a4fe992cd59488f2fea0d812dfc/src/events_watcher/evm/vanchor_watcher.rs#L63-L66

But looking at your logs here, it looks like that the event watcher did not even call `handle_event` for the VAnchorWatcher, can you expand a little bit and add more logs to the start of this method [here](https://github.com/webb-tools/relayer/blob/c3e29a7303008a4fe992cd59488f2fea0d812dfc/src/events_watcher/evm/vanchor_watcher.rs#L56-L61) to make sure it is being called and with what events?
