### ISSUE TITLE
[BUG] Old SignatureBridge proposal transactions are attempted while syncing

### ISSUE THREAD

**Issue by nepoche** [webb-tools/relayer#208]
# Current Behavior
If a relayer for a SignatureBridge starts syncing and sees an old proposal, the relayer will still attempt to send a transaction for the proposal:

https://gist.github.com/nepoche/3186788d08081f868fc32d850061e118

# Expected Behavior

The relayer should perform a 'dry-run' similar to the dry-run performed in private transaction relaying flows.

**Comment by dutterbutter** [comment]
@salman01zp similar to how we query for events, we should query the proposal nonce of the signature bridge. We can do a validation check of this nonce prior to proceeding. You can discuss with @drewstone if require further details.
