### ISSUE TITLE
[SPEC] Webb Relayer as crate (shared embeddable service)

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#212]
## Context

We designed the relayer from the start as CLI that runs as a standalone binary which will start a long running Http+Websocket Servers along with different background services.

With that being said, right now we are planning to change this into a reusable crate, specifically speaking we need to be able to easily embed the relayer into other rust programs, as a gadget on a blockchain, for example.

## Overview

The relayer main entry point, obviously, is the [`main`](https://github.com/webb-tools/relayer/blob/eb6e372d8d08ae1b1753e5cfa9d70248ccbb8df5/src/main.rs#L157) function, which does the following:

1. Parse the Command Line arguments (implicitly using the `paw` macro)
2. Setting up the global logger.
3. Check if there is a `.env` file somewhere to load that automatically into the current env.
4. Loads all the configurations files, parse them, and then creates `WebbRelayerConfig` from that.
5. **Creates `RelayerContext` from the provided configurations.**
6. **Setting up the storage back-end for the relayer state**
7. **Starts the relayer Http and Webscoket servers**
8. **Starts the relayer background services**
9. Does other stuff to handle the graceful shutdown (Ctrl+C signals for example).

That's it, if we look closely, we can see that the relayer could be easily made into a simple embeddable library of public free-functions that does the highlighted steps above (Step 5-8).

In fact, we can define the relayer as function of `WebbRelayerConfig` that returns a long running Future that can be easily spawned in the Tokio Runtime (or in the future if we decided to support other runtimes).

```rs
let fut = webb_relayer::run(config);
```

### Steps and Issues

1. Define what crates are used mainly for the CLI and what is being used for the relayer itself.
2. move `main.rs` into `lib.rs` and `relayer.rs`, then [define a binary](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries) points to `relayer.rs` in the `Cargo.toml`.
3. feature-flag anything related to the binary like the Command line parsing, dotenv, ..etc.
4. Expose the functions needed for `parsing` the configuration files and creating  `WebbRelayerConfig` and other functions that are related to the storage, http/ws services, and the background service.
5. Create a top-level function named `run` that is in somehow similar to a `main` function, that takes the `WebbRelayerConfig` and returns a long running task/future that can be spawned in a Tokio Runtime.
6. Publish the relayer crate to crates.io

### Tasks

- [x] #234 
- [x] #235 
- [x] #248

**Comment by dutterbutter** [comment]
Closed in #249
