### ISSUE TITLE
[SPEC] Create separate BridgeKey for each Resource

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#266]
## Overview
Currently, a single `BridgeKey` is constructed for all linked anchors to communicate AnchorUpdate proposals. Which is hardcoded with ChainId or SignatureBridge  address for all linked anchor to ensure we have single BridgeKey
- `VanchorWatcher` watches for vanchor events and then constructs `AnchorupdateProposals` for all linked Anchors and enqueues it into the queue with BridgeKey
   ```rust
    // now all we have to do is to send the data and the signature to the signature bridge.
        self.store.enqueue_item(
            SledQueueKey::from_bridge_key(bridge_key),
            BridgeCommand::ExecuteProposalWithSignature {
                data: proposal_bytes.to_vec(),
                signature: signature_bytes,
            },
        )?;
    ```
- We have `BridgeWatcher` which dequeues items from the queue using BridgeKey and executes proposals. (Single BridgeKey for all anchors)
    ```rust
  // BridgeWatcher for Evm
  let my_chain_id = client
        .get_chainid()
        .map_err(Into::into)
        .map_err(backoff::Error::transient)
        .await?;
  let bridge_key = BridgeKey::new(my_address, my_chain_id);
  let key = SledQueueKey::from_bridge_key(bridge_key);
  loop {
        let result = match store.dequeue_item(key)? {..}
     }

  //  for substrate
  let target = webb_proposals::SubstrateTargetSystem::builder()
      .pallet_index(0)
      .tree_id(chain_id.as_u32())
      .build();
  let target_system = webb_proposals::TargetSystem::Substrate(target);
  let my_chain_id = webb_proposals::TypedChainId::Substrate(chain_id.as_u32());
  let bridge_key = BridgeKey::new(target_system, my_chain_id);
  let key = SledQueueKey::from_bridge_key(bridge_key);
  loop {
    let result = match store.dequeue_item(key)? {..}
  }
  ```

## Proposed Changes
Create a separate queue for each resource with `ResourceId` as BridgeKey. VanchorWatchers will enqueue proposals to these queues based upon BridgeKey and BridgeWatchers will dequeue and process events from these queues.

```rust
// Bridge watcher: separate queue for each resource_id
let all_resources = api.signature_bridge.storage.resources();
loop {
    for resource in all_resources {
        key = BridgeKey::from_resource_id(resource)
        let result = match store.dequeue_item(key)? {
            Some(cmd) => {
                self.handle_cmd(
                    chain_id,
                    store.clone(),
                    api.clone(),
                    cmd,
                )
                .await
            }
    }
}

/// Creates new BridgeKey from ResourceId
    pub fn from_resource_id(resource_id: webb_proposals::ResourceId) -> Self {
        Self {
            target_system: resource_id.target_system(),
            chain_id: resource_id.typed_chain_id()
        }
    }
}
```

**Comment by drewstone** [comment]
Why do we have a bridge key? Can we instead just use resource IDs?

**Comment by drewstone** [comment]
Also @salman01zp, I would recommend taking a look at this pallet: https://github.com/webb-tools/dkg-substrate/tree/master/pallets/bridge-registry.

The way we are currently thinking about storing bridge metadata on chain is simply as a `Vec<ResourceId>`. On this pallet, we index bridges numerically and increment the index when we see new resource ids that are not linked to existing bridges.

Therefore, on the relayer, it may eventually be possible (and you should investigate this more) to simply query the parachain for the bridges, their resource IDs, and create any relevant maps locally to handle updates to a bridge's anchors.

**Comment by drewstone** [comment]
The other alternative which seems potentially better is to also query the neighboring linked anchors using the `VAnchor`'s `EdgeList`.
