### ISSUE TITLE
[TASK] Store EncryptedCommitments similarly to leaves on the relayer

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#267]
## Overview

Currently `NoteAccount`, the users encrypted DepositNotes / ChangeNotes, and registration checks are all stored / tracked in `localStorage` which is only available to a specific machine. We want to improve the users experience by utilizing the relayer network to store, and handle registration checks so that the user may access their `NoteAccount` and secret notes by querying the relayers instead, as well as, be able to immediately deposit on a fresh machine if they have registered on-chain previously. This will also be good to have in place for the second iteration of enabling transfers between two registered accounts. 

### Task Checklist

- [ ]  [TASK] Store EncryptedCommitments similarly to leaves on the relayer.
    - Users should be able to access their `NoteAccount` and secret notes by querying the relayers
- [ ]  [TASK] Implement registration checks on an api exposed relayer network
    - Currently registration is tracked in `LocalStorage` which is only available on a specific machine. Users should be able to immediately deposit on a fresh machine if they have registered on-chain previously.
    - Update webb-dapp to fetch registration details from relayer endpoint (i.e. `api/v1/isRegistered/<xxx>` ) rather than `LocalStorage`

### Relevant Links

- [Note Account implementation details](https://www.notion.so/hicommonwealth/Feature-1-UTXO-Note-Management-24194cdbfee14b688e6b88f2c6e3e20d)
   - [PR - Note Account](https://github.com/webb-tools/webb-dapp/pull/494)
- [Current registration flow](https://www.notion.so/hicommonwealth/Feature-4-User-Registration-Flow-c8639284eec3491bacb0d232dc0e98a3)

**Comment by drewstone** [comment]
@dutterbutter if users are querying relayers for their encryptions this exposes their privacy. Did you consider this?

**Comment by dutterbutter** [comment]
@drewstone I don't think it does compromise privacy as we would be fetching all EncryptedCommitments similarly as we do for leaves fetching, no?

**Comment by dutterbutter** [comment]
Closed in #275
