### ISSUE TITLE
[TASK] Update the naming and docs for variables, files, and roles of the relayer

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#295]
# Overview
There is a mixing of naming schemes that we now have `private-tx`, `relay-tx`, etc. We should identify exact names of things now and update the docs and variable/files so that we can prevent this in the future.

## Relayer roles
Some we can consider wrapping into a single role for simplicity. I will list what I imagine exists today.
- Running a private transaction relayer
- Running a signed proposal relayer
- Running an anchor update event listener and leaves watcher (for each anchor type)
- Running a light-client relayer (block headers)

## Involved
@shekohex @salman01zp @nepoche @dutterbutter

**Comment by salman01zp** [comment]
### Relayer Terminologies
- **Signed-proposal-relaying**
   Relaying signed proposals to the signature bridges.
- **Transaction-relaying**
   create zk proofs and send them to the relayer for the relayer to execute.
- **Data-querying**
   Access to relayer data API endpoints (leaves, encrypted leaves)
- **Block-header-relaying**

@drewstone @shekohex  what do you think?

**Comment by dutterbutter** [comment]
Closed in #300
