### ISSUE TITLE
[TASK] Support Reading Secrets from a file

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#298]
### Overview
Currently for EVM based chains configurations, we do support supplying the `PrivateKey` as either a Hex value hardcoded in the config file, or through an Environment Variable that points to the Private Key in a hex encoded string. 

### Requirement
We need also to support reading the private key as a hex value from a file, that would enable a more secure way if running a relayer under a user and that user only the one has access to read to that file.

The config file should be something like this

```toml
private-key = "file://path/to/privatekey.hex"
```
 
code could be found here: 
https://github.com/webb-tools/relayer/blob/41100a2e1d15bf9a51df99817fbf6421c6733b16/crates/relayer-types/src/private_key.rs#L52-L76

**Comment by drewstone** [comment]
We should also support reading a mnemonic from file as well.
