### ISSUE TITLE
[TASK] Remove actions-rs actions from CI

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#317]
## Motivation
Since action-rs is no longer maintained it will be better to opt for alternative solutions.
 For more details refer [action-rs/#2216](https://github.com/actions-rs/toolchain/issues/216)

## Solution
- Use [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) instead of actions-rs/toolchain
- Use [rustsec/audit-check](https://github.com/rustsec/audit-check) (fork of actions-rs/audit-check) instead of actions-rs/audit-check
- Use `cargo` directly instead of actions-rs/cargo

**Comment by dutterbutter** [comment]
@salman01zp I think this extends to all our rust repos.
