### ISSUE TITLE
[TASK] Implement validation over leaf caching against chain state

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#350]
# Overview
Use a local merkle tree instance in the relayer to validate the leaves against the merkle root on chain. You can use the merkle tree found in: https://github.com/webb-tools/zero-knowledge-gadgets/blob/master/arkworks/native-gadgets/src/merkle_tree.rs.

Each time we add a leaf, it should be imperative to check the state of our local tree against the state on-chain. If it matches, we can proceed. If it doesn't match we need to:
- Clear our cache
- Start over (fetch all the events using the fast sync for events)
- Rebuild the tree
- Validate and continue until we get this right.

**Comment by shekohex** [comment]
Closes by #354
