### ISSUE TITLE
[TASK] Add Tests for Substrate governor updates flow

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#367]
## Overview
Add governor update test case for substrate based chains. Relayer should watch for `PublicKeySignatureChanged` and relay `set_maintainer` transaction to substrate chain.

```rust
// msg = nonce+dkg_key
 let mut message = nonce.to_be_bytes().to_vec();
 message.extend_from_slice(&new_maintainer);

 let set_maintainer_call = SetMaintainer {
            message: BoundedVec(message.clone()),
            signature: BoundedVec(signature.clone()),
 };

```

----
### Checklist
- [ ] Update relayer code to construct `msg = nonce+dkg_key`
- [ ] Write governor update test

**Comment by salman01zp** [comment]
closed by #371
