### ISSUE TITLE
Fix outdated config files

### ISSUE THREAD

**Issue by Nutomic** [webb-tools/relayer#368]
I tried running with config files `development/evm-localdkg` and `local-substrate`, both of them were throwing lots of errors about missing fields.

It would be nice to add some test cases which try to parse all the config files, that way we would catch in CI if something is wrong.

Edit: .env.example files are also wrong, lines with `WEBB_SUBSTRATE_LOCALDKG_ENABLED=true` should be removed as they case error "substrate.localdkg: missing field `name`"

**Comment by shekohex** [comment]
Closed by #369
