### ISSUE TITLE
[TASK] Update the Relayer deployment for the dAPP Integration v0.5.0-rc9

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#382]
### Overview

Update the Relayer(s) that is used by the current dApp deployment to the latest release of the relayer.

### Task Checklist

- [x] Update Relayer 4
- [x] Update Relayer 5

Please note that Relayer 1, 2, 3 are not going to be updated until the dApp team rollout the staging to the production env.

Related to: https://github.com/webb-tools/webb-dapp/pull/1060

**Comment by salman01zp** [comment]
Relayer 5 : Live with mocked backend
Relayer 4:  Live with DKG backend
