### ISSUE TITLE
[TASK] Bridge Registry  pallet Integration  for substrate chains

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#448]
## Overview

We need to fetch linked anchors from the bridge integration pallet for substrate-based chains just like we did for EVM [here](https://github.com/webb-tools/relayer/issues/358).

This will altogether remove linked anchors from the relayer configuration

## Checklist
- [x] Fetch linked anchors from the bridge registry pallet
- [x] Update handlers to use linked anchors from the bridge registry pallet

**Comment by shekohex** [comment]
Closed by #447
