### ISSUE TITLE
[TASK] Use tangle runtime rust bindings in relayer

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/relayer#460]
## Overview
Currently, the relayer uses `substrate-runtime` and `dkg-runtime`  [metadata](https://docs.rs/webb/0.5.21/webb/substrate/index.html) separately to interact with respective nodes. But since the relayer will be interacting with just the `tangle` node, we should update the relayer code base to use rust bindings for tangle-runtime metadata.

We can also remove substrate-runtime and dkg-runtime from webb-rs.

**Comment by shekohex** [comment]
Increased the effort as it looks like this PR is touching a lot of other areas.
