### ISSUE TITLE
[TASK] Make use of `TimeLag` Middleware for safety against reorgs on EVM Chains

### ISSUE THREAD

**Issue by shekohex** [webb-tools/relayer#509]
### Overview

We currently have `block-confirmations` in the configurations, but we recently removed the usage of this intuitively in #501 What we should do instead wrap that into [ethers](https://docs.rs/ethers/latest/ethers/index.html)::[middleware](https://docs.rs/ethers/latest/ethers/middleware/index.html)::[timelag](https://docs.rs/ethers/latest/ethers/middleware/timelag/index.html)::[TimeLag](https://docs.rs/ethers/latest/ethers/middleware/timelag/struct.TimeLag.html#)  instead and use the configured value of `block-confirmations` here. So that by default, everything is lagged by this number of blocks.

Notice that, even the `latest_block_number` will be lagged by the block-confirmations here. We shall decide wisely which parts may need this features and which parts isn't.

### Task Checklist

- [ ] Change our type `EthersClient` to be wrapped `TimeLag` middleware.
- [ ] Update tests
- [ ] Update docs.

**Comment by salman01zp** [comment]
Adding `TimeLag`middleware for the following features.
- Event Watchers ✅ 
- Event Handlers ✅ 
- Tx-queue  ✅ 
- Tx-relay   ❌
