### ISSUE TITLE
[TASK] Investigate optimization/multi-call possibilities on the relayer.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#520]
# Overview
We are exhausting our INFURA api each day, quite early every day. We need to continue to optimize the RPC calls we are making. However we are fetching data, we should find new ways of consolidating these calls.

The most common calls are:
- getTxByHash
- getLogs
- etc.

## Checklist
- [x] Investigate where we can leverage multi-call
- [x] Investigate if filtering for ALL events is causing a blowup in RPC calls, if so, optimize by fetching only the events we handle
- [ ] Document ways of using multi-call for those RPC calls
- [ ] Create tasks to implement them.

**Comment by drewstone** [comment]
Is it possible that we can query over a larger interval of blocks with a single query?

**Comment by salman01zp** [comment]
Yes, we have a configuration to fetch larger interval.
```rust
    /// The maximum number of events to fetch in one request.
    #[serde(default = "defaults::max_blocks_per_step")]
    pub max_blocks_per_step: u64,
```

Once the relayer is synced with the latest block it will wait for cool down period and fetch next events as following
```rust
// block: last processed block number 
// step: max_blocks_per_step  (default 500 blocks)
// target_block_number: Latest block number on chain (after cool down)
 let dest_block = core::cmp::min(block + step, target_block_number);
 ```
 
 In order to have a large interval range we need to have a large cool-down period. Maybe we add dynamic time interval
