### ISSUE TITLE
[TASK] Documentation for creating a minimal contract event listener/handler

### ISSUE THREAD

**Issue by drewstone** [webb-tools/relayer#574]
# Overview
We should have a minimal example and README for using certain libraries here, namely the event watcher. We should do so so that it other developers can leverage it for their apps without being burdened by other high-level software we write around our own event listening wrappers.

This is a good example of a simple document that is high value: https://github.com/a16z/Lasso/blob/master/HowToTable.md.

**Comment by shekohex** [comment]
Good idea.
