### ISSUE TITLE
[CHORE] aarch64-apple-darwin target does not exist in available releases

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/relayer#72]
### Issue Description

- Running `curl -fsSL https://git.io/get-webb-relayer.sh | sh` or `install.sh` commands to install **`webb-relayer`** on apple silicon fails with the following error

```
curl: (22) The requested URL returned error: 404
```

- The issue seems to be there is no `aarch64-apple-darwin` target available in the [releases](https://github.com/webb-tools/relayer/releases). 

### Solution

- Running the `x86_64-apple-darwin` target works fine but an update to the script to defer to `x86_64-apple-darwin` or adding a `aarch64-apple-darwin` target would suffice.

**Comment by shekohex** [comment]
Thank you! currently, we have not added support for Apple ARM support yet, but we will try to do the update as soon as possible.
for now, you could try using Docker or the x86_64 build.
