### ISSUE TITLE
[BUG] relayer doesn't return beneficiary/account for substrate on the `/info` call

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/relayer#84]
# Overview
Currently, we aren't sending the relayer address in the `/info` call. We should have the key in the configuration that we can generate the address from. We should return this as well from the API.

This is the configuration of the relayer on Substrate
```
[substrate.localnode]
http-endpoint = "http://localhost:9933/"
ws-endpoint = "ws://localhost:9944/"
runtime = "WebbProtocol"
suri = "//Alice"
pallets=[]
```

## Task
- [x] #85

**Comment by shekohex** [comment]
Closed by #86
